name: Publish to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
    with:
      flutter-version: '2.5.0'
    - run: flutter pub get
    - run: flutter build web --web-renderer html